-- This is simply a stub file create automatically by the kvdriver tool.
--
-- Feel free to change things around, but keep in mind you might break
-- things up.
-- 
-- Notice also this file is generated by the kvdriver init command. It's
-- not suposed to change after that.. so.... have fun messing around!




--------------
-- Ada 2005 --
--------------
with Ada.Exceptions;
with Ada.Strings.Unbounded;	use Ada.Strings.Unbounded;
with Ada.Text_IO;		use Ada.Text_IO;


-------------------
-- KOW Framework --
-------------------
with KOW_View;



with @_project_name_@_Setup;


procedure @_project_name_@_Cli is
	Conf		: constant AWS.Config.Object := AWS.Config.Get_Current;
begin
	-------------------
	-- Run the Setup --
	-------------------
	@_project_name_@_Setup( false );
	-- the setup process is where the entire KOW Framework is initialized. :)

	-- TODO :: the command line stuff here
exception
	when E : Others =>
		Ada.Text_IO.Put_Line( "=======================================" );
		Ada.Text_IO.Put_Line( "=======================================" );
		Ada.Text_IO.Put_Line( "=======================================" );
		Ada.Text_IO.Put_Line( Ada.Exceptions.Exception_Information( E ) );
		Ada.Text_IO.Put_Line( "=======================================" );
		Ada.Text_IO.Put_Line( "=======================================" );
		Ada.Text_IO.Put_Line( "=======================================" );

end @_project_name_@_Cli;
